# Site settings
title: "FATAL ERROR: Signal Received: SIGSEGV (11)"
description: "Jahziel talks computers ğŸ‘¨â€ğŸ’»"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink: /:year/:title
github: "jahzielv"
twitter: "jahz_v"
email: "jve@jahz.co"
disqus-id: "" #leave blank if you dont want comments.

# Build settings
markdown: kramdown
sass:
    style: :compressed
